# -*- coding: utf-8 -*-
{
'name': 'Localización Paraguay Rapidsoft',
'version': '1.0.1',
'category': 'Update',
'description': """Módulo de localización y configuración básica para Paraguay 15
""",
'author': 'Rapidsoft',
'website': 'http://www.rapidsoft.com.py',
# 'depends': ['l10n_py','l10n_py_toponyms','partner_ruc','base','account','account_accountant','stock','account_voucher','purchase_stock','assets_paraguay'],
'depends': ['l10n_py_toponyms','partner_ruc','base','account','account_voucher','sale','purchase', 'stock'],
'data': [
        'data/tipo_comprobante.xml',
        'views/account_view.xml',
        'views/account_move.xml',
	    'security/security.xml',
	    'security/ir.model.access.csv',
        'views/company_view.xml',
        'views/invoice_view.xml',
        'views/hechauka.xml',
        'views/motivo_anulacion_view.xml',
        'views/users_view.xml',
        'views/purchase_view.xml',
        'views/sale_view.xml',
        'views/tipo_comprobante_view.xml',
	    'views/documentos_timbrados_view.xml',
        'security/reglas.xml',
        'sequences/asiento_sequence.xml',
        'data/res_bank_data.xml',
        'reports/config.xml',
        'reports/voucher_report.xml',
        'reports/voucher_report_supplier.xml',
],
        'installable': True,
        'auto_install': False,
        'application': True,
        'license': 'LGPL-3',

}
