# -*- coding: utf-8 -*-
from odoo import fields, models, exceptions, api
from datetime import datetime, timedelta
from dateutil.parser import parse
from odoo.exceptions import ValidationError
import time
import logging
import pytz

_logger = logging.getLogger(__name__)


class HrEmployeeInh(models.AbstractModel):
    _inherit = "hr.employee.base"
    primer_nombre = fields.Char(string='Primer nombre')
    segundo_nombre = fields.Char(string='Segundo nombre')
    primer_apellido = fields.Char(string='Primer apellido')
    segundo_apellido = fields.Char(string='Segundo apellido')

    tipo_pago_set = fields.Selection([
        ('1', 'SALARIOS'),
        ('2', 'HONORARIOS PROFESIONALES'),
        ('3', 'HONORARIOS POR SERVICIOS PERSONALES'),
        ('4', 'DIVIDENDOS, UTILIDADES Y EXCEDENTES'),
        ('5', 'GANANCIAS POR VENTA DE MUEBLES E INMUEBLES'),
        ('6', 'INTERESES, COMISIONES O RENDIMIENTOS DE CAPITAL'),
        ('7', 'OTROS QUE ESTABLECE EL ART. 20 DEL DECRETO 9371/12'),
        ('8', 'RECIBO DE SUELDO'),
        ('9', 'NINGUNO')
    ], string="Tipo de Pago")

    tipo_empleado_set = fields.Selection([
        ('1', 'DEPENDIENTE'),
        ('2', 'INDEPENDIENTE')
    ], string="Tipo de Empleado")

    departamento_set = fields.Selection([
        ('1', 'CAPITAL'),
        ('2', 'CONCEPCION'),
        ('3', 'SAN PEDRO'),
        ('4', 'CORDILLERA'),
        ('5', 'GUAIRA'),
        ('6', 'CAAGUAZU'),
        ('7', 'CAAZAPA'),
        ('8', 'ITAPUA'),
        ('9', 'MISIONES'),
        ('10', 'PARAGUARI'),
        ('11', 'ALTO PARANA'),
        ('12', 'CENTRAL'),
        ('13', 'NEEMBUCU'),
        ('14', 'AMAMBAY'),
        ('15', 'PTE. HAYES'),
        ('16', 'BOQUERON'),
        ('17', 'ALTO PARAGUAY'),
        ('18', 'CANINDEYU')
    ], string="Departamento")

    distrito_set = fields.Selection([
        ('1', 'ASUNCION (DISTRITO)'),
        ('2', 'CONCEPCION (MUNICIPIO)'),
        ('3', 'SAN LAZARO'),
        ('4', 'SAN CARLOS'),
        ('5', 'BELEN'),
        ('6', 'LORETO'),
        ('7', 'HORQUETA'),
        ('8', 'SAN SALVADOR'),
        ('9', 'YBY YA\'U'),
        ('270', 'SARGENTO JOSE FELIZ LOPEZ'),
        ('10', 'SAN PEDRO DE YCYAMANDYYU'),
        ('11', 'ANTEQUERA'),
        ('12', 'GRAL. E.AQUINO'),
        ('13', 'ITACURUBI DEL ROSARIO'),
        ('14', 'SAN ESTANISLAO (SANTANI)'),
        ('15', 'LIMA'),
        ('16', 'NUEVA GERMANIA'),
        ('17', 'TACUATI'),
        ('18', 'UNION'),
        ('19', '25 DE DICIEMBRE'),
        ('20', 'VILLA DEL ROSARIO'),
        ('21', 'YATAITY DEL NORTE'),
        ('22', 'ISIDORO RESQUIN'),
        ('23', 'CHORE'),
        ('24', 'SAN PABLO'),
        ('25', 'SAN JOSE DEL ROSARIO'),
        ('220', 'SAN JOSE DEL ROSARIO'),
        ('226', 'CAPIIBARY'),
        ('245', 'YRYBUCUA'),
        ('26', 'CAACUPE'),
        ('27', 'ALTOS'),
        ('28', 'ARROYOS Y ESTEROS'),
        ('29', 'ATYRA'),
        ('30', 'CARAGUATAY'),
        ('31', 'EMBOSCADA'),
        ('32', 'EUSEBIO AYALA'),
        ('33', 'ISLA PUCU'),
        ('34', 'ITACURUBI DE LA CORDILLERA'),
        ('35', 'JUAN DE MENA'),
        ('36', 'NUEVA COLOMBIA'),
        ('37', 'PIRIBEBUY'),
        ('38', '1RO.DE MARZO'),
        ('39', 'SAN BERNARDINO'),
        ('40', 'SANTA ELENA'),
        ('41', 'TOBATI'),
        ('42', 'VALENZUELA'),
        ('43', 'LOMA GRANDE'),
        ('44', 'SAN JOSE OBRERO'),
        ('214', 'MBOCAYATY DEL YHAGUY'),
        ('45', 'VILLARRICA'),
        ('46', 'SAN SALVADOR'),
        ('47', 'BORJA'),
        ('48', 'INDEPENDENCIA(R.D.MELGAREJO)'),
        ('49', 'GRAL.EUGENIO A.GARAY'),
        ('50', 'CNEL.MARTINEZ'),
        ('51', 'JOSE FASSARDI'),
        ('52', 'FELIX PEREZ CARDOZO'),
        ('53', 'MAURICIO JOSE TROCHE'),
        ('54', 'ITAPE'),
        ('55', 'ITURBE'),
        ('56', 'MBOCAYATY'),
        ('57', 'NATALICIO TALAVERA'),
        ('58', 'ÑUMI'),
        ('59', 'YATAITY'),
        ('60', 'DR.BOTREL'),
        ('225', 'PASO YOBAY'),
        ('246', 'SIN EQUIVALENCIA'),
        ('265', 'TEBICUARY'),
        ('61', 'CNEL.OVIEDO'),
        ('62', 'CAAGUAZU'),
        ('63', 'CARAYAO'),
        ('64', 'CECILIO BAEZ'),
        ('65', 'NUEVA LONDRES'),
        ('66', 'SAN JOAQUIN'),
        ('67', 'SAN JOSE DE LOS ARROYOS'),
        ('68', 'YHU'),
        ('69', 'JUAN MANUEL FRUTOS'),
        ('70', 'REPATRIACION'),
        ('71', 'SANTA ROSA DEL MBUTUY'),
        ('72', 'J.EULOGIO ESTIGARRIBIA'),
        ('73', 'JOSE D.OCAMPOS'),
        ('74', 'R.I.3 CORRALES'),
        ('75', 'RAUL A.OVIEDO'),
        ('76', 'MCAL.F.SOLANO LOPEZ'),
        ('227', '3 DE FEBRERO'),
        ('228', 'SIMON BOLIVAR'),
        ('229', 'LA PASTORA'),
        ('237', 'VAQUERIA'),
        ('244', 'ESCULIES'),
        ('275', 'TEMBIAPORA'),
        ('77', 'CAAZAPA'),
        ('78', 'BUENA VISTA'),
        ('79', 'GRAL.H.MORINIGO'),
        ('80', 'MACIEL'),
        ('81', 'MOISES BERTON'),
        ('82', 'SAN JUAN NEPOMUCENO'),
        ('83', 'ABAI'),
        ('84', 'TAVAI'),
        ('85', 'YEGROS'),
        ('86', 'YUTY'),
        ('272', '3 DE MAYO'),
        ('87', 'ENCARNACION'),
        ('88', 'BELLA VISTA'),
        ('89', 'CAMBYRETA'),
        ('90', 'CAPITAN MEZA'),
        ('91', 'CARMEN DEL PARANA'),
        ('92', 'CAPITAN MIRANDA'),
        ('93', 'CORONEL BOGADO'),
        ('94', 'FRAM'),
        ('95', 'GRAL.ARTIGAS'),
        ('96', 'GRAL.DELGADO'),
        ('97', 'HOHENAU'),
        ('98', 'JESUS'),
        ('99', 'OBLIGADO'),
        ('100', 'SAN COSME Y DAMIAN'),
        ('101', 'SAN PEDRO DEL PARANA'),
        ('102', 'NUEVA ALBORADA'),
        ('103', 'TRINIDAD'),
        ('104', 'NATALIO'),
        ('105', 'JOSE LEANDRO OVIEDO'),
        ('106', 'SAN RAFAEL DEL PARANA'),
        ('107', 'CARLOS A.LOPEZ'),
        ('108', 'JULIO D.OTAÑO'),
        ('109', 'EDELIRA'),
        ('110', 'SAN JUAN DEL PARANA'),
        ('111', 'LA PAZ'),
        ('112', 'TOMAS R.PEREIRA'),
        ('113', 'YATYTAY'),
        ('114', 'HERIBERTA S.DE IGLESIAS'),
        ('221', 'PIRAPO'),
        ('232', 'ITAPUA POTY'),
        ('243', 'FEDERICO CHAVEZ'),
        ('115', 'SAN JUAN BAUTISTA'),
        ('116', 'AYOLAS'),
        ('117', 'SAN IGNACIO'),
        ('118', 'SAN MIGUEL'),
        ('119', 'SAN PATRICIO'),
        ('120', 'SANTIAGO'),
        ('121', 'SANTA MARIA'),
        ('122', 'SANTA ROSA'),
        ('123', 'VILLA FLORIDA'),
        ('124', 'YABEBYRY'),
        ('125', 'PARAGUARI'),
        ('126', 'ACAHAY'),
        ('127', 'CAAPUCU'),
        ('128', 'CABALLERO'),
        ('129', 'CARAPEGUA'),
        ('130', 'LA COLMENA'),
        ('131', 'ESCOBAR'),
        ('132', 'MBUYAPEY'),
        ('133', 'PIRAYU'),
        ('134', 'QUIINDY'),
        ('135', 'ROQUE GONZALEZ'),
        ('136', 'SAPUCAI'),
        ('137', 'YBYCUI'),
        ('138', 'QUYQUYHO'),
        ('139', 'YBYTYMI'),
        ('140', 'TEBICUARY MI'),
        ('141', 'YAGUARON'),
        ('142', 'HERNANDARIAS'),
        ('143', 'DOMINGO MARTINEZ DE IRALA'),
        ('144', 'ÑACUNDAY'),
        ('145', 'CIUDAD DEL ESTE'),
        ('146', 'JUAN LEON MALLORQUIN'),
        ('147', 'ITAKYRY'),
        ('148', 'JUAN E.O\'LEARY'),
        ('149', 'PUERTO PTE.FRANCO'),
        ('150', 'YGUAZU'),
        ('151', 'SAN CRISTOBAL'),
        ('209', 'SANTA RITA'),
        ('210', 'MINGA GUAZU'),
        ('211', 'LOS CEDRALES'),
        ('212', 'SAN ALBERTO'),
        ('213', 'MINGA PORA'),
        ('215', 'NARANJAL'),
        ('216', 'SANTA ROSA DEL MONDAY'),
        ('217', 'IRUÑA'),
        ('219', 'MBARACAYU'),
        ('239', 'SANTA FE DEL PARANA'),
        ('240', 'NUEVA ESPERANZA'),
        ('152', 'AREGUA'),
        ('153', 'CAPIATA'),
        ('154', 'FERNANDO DE LA MORA'),
        ('155', 'GUARAMBARE'),
        ('156', 'ITA'),
        ('157', 'ITAUGUA'),
        ('158', 'LIMPIO'),
        ('159', 'LUQUE'),
        ('160', 'MARIANO ROQUE ALONSO'),
        ('161', 'ÑEMBY'),
        ('162', 'NUEVA ITALIA'),
        ('163', 'SAN ANTONIO'),
        ('164', 'SAN LORENZO'),
        ('165', 'VILLA ELISA'),
        ('166', 'VILLETA'),
        ('167', 'YPACARAI'),
        ('168', 'YPANE'),
        ('169', 'LAMBARE'),
        ('170', 'J.AUGUSTO SALDIVAR'),
        ('277', 'LOMA PYTA'),
        ('171', 'PILAR'),
        ('172', 'ALBERDI'),
        ('173', 'CERRITO'),
        ('174', 'DESMOCHADOS'),
        ('175', 'GUAZU CUA'),
        ('176', 'HUMAITA'),
        ('177', 'ISLA UMBU'),
        ('178', 'LAURELES'),
        ('179', 'PASO DE PATRIA'),
        ('180', 'MAYOR J.D.MARTINEZ'),
        ('181', 'SAN JUAN DE ÑEEMBUCU'),
        ('182', 'TACUARAS'),
        ('183', 'VILLA OLIVA'),
        ('184', 'VILLALBIN'),
        ('203', 'GRAL.JOSE EDUVIGIS DIAZ'),
        ('205', 'VILLA FRANCA'),
        ('231', 'VILLALBIN'),
        ('185', 'PEDRO JUAN CABALLERO'),
        ('186', 'BELLA VISTA'),
        ('187', 'CAPITAN BADO'),
        ('278', 'KARAPAI'),
        ('188', 'VILLA HAYES'),
        ('189', 'BENJAMIN ACEVAL(MONTE SOCIEDAD'),
        ('190', 'PTO.PINAZCO'),
        ('191', 'NANAWA'),
        ('206', 'POZO COLORADO'),
        ('242', 'JOSE FALCON'),
        ('192', 'MCAL.ESTIGARRIBIA'),
        ('193', 'BOQUERON'),
        ('194', 'PEDRO P.PEÑA'),
        ('234', 'GRAL.EUGENIO A.GARAY'),
        ('259', 'FILADELFIA'),
        ('195', 'FUERTE OLIMPO'),
        ('196', 'BAHIA NEGRA'),
        ('218', 'PUERTO CASADO'),
        ('223', 'PUERTO GUARANI'),
        ('233', 'MAYOR PABLO LAGERENZA'),
        ('197', 'SAN ISIDRO DEL CURUGUATY'),
        ('198', 'VILLA YGATIMI'),
        ('199', 'YPEJHU'),
        ('200', 'CORPUS CHRISTI'),
        ('201', 'ITANARA'),
        ('202', 'FRANCISCO CABALLERO ALVAREZ'),
        ('207', 'SALTO DEL GUAIRA'),
        ('235', 'LA PALOMA'),
        ('236', 'KATUETE'),
        ('238', 'NUEVA ESPERANZA'),
        ('241', 'YASY KAÑY'),
        ('271', 'YBYRAROBANA'),
        ('274', 'YBY PYTA')
    ], string="Distrito")