from . import hr_income_expense
from . import hr_employee
from . import hr_payslip
from . import hr_leave
from . import hr_leave_type_inh
from . import hr_contract
from . import work_entries
from . import hr_payslip_structure
from . import hr_payslip_run_structure