from . import hr_cedulaLegajo
from . import hr_antecedentePolicial
from . import hr_grupo_familiar
from . import hr_antecenteJudicial
from . import hr_curriculumLegajo
from . import hr_tituloLegajo
from . import hr_contrato_confidencialidad
from . import hr_reglamento_interno
from . import hr_contrato_trabajo
from . import hr_ips
from . import hr_ministerio_trabajo
