{
    'name': 'Gestión de préstamos a cuotas',
    'version': '15.0.1.0.0',
    'summary': 'Manage Loan Requests',
    'description': """
        Le ayuda a gestionar las Solicitudes de Préstamo del personal de su empresa        """,
    'category': 'Human Resources',
    'author': "SATI",
    'company': 'SATI',
    'maintainer': 'SATI',
    'website': "https://sati.com.py/",
    'depends': ['base', 'hr_payroll', 'hr', 'account', 'hr_documenta'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/hr_loan_seq.xml',
        'views/hr_loan.xml',
        'views/lista_de_descuentos.xml',
        'views/hr_payslib_inh.xml',
        'reports/report_config.xml',
        'reports/report_template.xml',
    ],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
}
